accord/urls.py
from django.urls import path
from . import views

app_name = 'accord'

urlpatterns = [
    path('', views.index, name='index'),
]

authApp/urls.py
from django.urls import path
from django.contrib.auth import views as authLib 
from . import views

app_name = 'authApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signup/', views.signup, name='signup'),
    path('login/', authLib.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', authLib.LogoutView.as_view(template_name='logout.html', next_page=None), name='logout'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('confirm/<int:index>', views.confirm, name='confirm'),
]

like/urls.py
from django.urls import path
from . import views

app_name = 'like'

urlpatterns = [
    path('', views.index, name='index'),
    path('like/', views.like, name='like'),
    path('leaderboard/', views.leaderboard, name='leaderboard')
]

qasqus/qasqus/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

qasqus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('board.urls')),
    path('accord/', include('accord.urls')),
    path('book/', include('like.urls')),
    path('auth/', include('authApp.urls')),
]

accord/models.py
from django.db import models

# Create your models here.

authApp/models.py
from django.db import models

# Create your models here.

board/models.py
from django.db import models
from django import forms
from django.forms import ModelForm

# Create your models here.
class Message(models.Model):
    name = models.CharField(max_length = 255)
    text = models.TextField()

    def __str__(self):
        return self.name

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

like/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    api_id = models.CharField(max_length=20, primary_key=True)
    title = models.CharField(max_length=100)
    authors = models.CharField(max_length=100)
    likes_count = models.IntegerField(default=1)

    def as_dict(self):
        return {
        "title": self.title,
        "authors": self.authors,
        "likes_count": self.likes_count,
        }

    def __str__(self):
        return self.title

accord/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'accord.html')

authApp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

def index(request):

	return render(request, 'auth.html')

@login_required
def dashboard(request):

	return render(request, 'dashboard.html')

def signup(request):

	if request.method == 'POST':
		form = UserCreationForm(request.POST)

		if form.is_valid():
			form.save()

			return redirect('authApp:dashboard')
	else:
		form = UserCreationForm()

	return render(request, 'signup.html', {'form' : form})

board/views.py
from django.shortcuts import render, redirect

from .models import Message, MessageForm

# Form and all MSG.
def index(request):
    msg = Message.objects.all()
    form = MessageForm()

    return render(request, 'index.html', {'msg' : msg, 'form' : form})

def confirm(request, index):
    msg = Message.objects.all()

    if request.method == 'POST':
            name = request.POST['name']
            text = request.POST['text']

            bucket = Message(name = name, text = text)

            if index == 1:
                return render(request, 'index.html', {'msg' : msg, 'bucket' : bucket})

            elif index == 2:
                bucket.save()

    return redirect('board:index')

like/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.urls import resolve, reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

from .models import Book

def index(request): 
    return render(request, 'book.html')

@csrf_exempt
def like(request): 
	if request.method == 'POST':
		# Get raw data from post request
	    id = request.POST['id']
	    title = request.POST['title']
	    authors = request.POST['authors']

	    bookModel, status = Book.objects.get_or_create(api_id=id, title=title, authors=authors)
	    if status: 
	        bookModel.save()
	    else:
	        bucket = Book(api_id=id, title=bookModel.title, authors=bookModel.authors, likes_count=bookModel.likes_count+1)
	        bucket.save()

	    return JsonResponse(bookModel.as_dict())

def leaderboard(request):
	# Take only the first 5
	leaderboards = [bookModel.as_dict() for bookModel in Book.objects.order_by('-likes_count')[:5]]

	return JsonResponse({'leaderboards' : leaderboards})

accord/templates/accord.html
{% extends 'base.html' %}
{% load static %}

{% block title %}QasQus Accord{% endblock %}

{% block body %}
<div class="text-center">
    <div class="wrapper">

        <div class="acc-item 1">
            <div class="acc-header">
                <div class="float-right">
                    <i class="move-up"></i>
                    <i class="move-down"></i>
                </div>
                <div class="title">Aktiviti 1</div>
            </div>
            <div class="acc-body">
                <p>Lorem Ipsum</p>
            </div>
        </div>

        <div class="acc-item 2">
            <div class="acc-header">
                <div class="float-right">
                    <i class="move-up"></i>
                    <i class="move-down"></i>
                </div>
                <div class="title">Aktiviti 2</div>
            </div>
            <div class="acc-body">
                <p>Lorem Ipsum</p>
            </div>
        </div>

        <div class="acc-item 3">
            <div class="acc-header">
                <div class="float-right">
                    <i class="move-up"></i>
                    <i class="move-down"></i>
                </div>
                <div class="title">Aktiviti 3</div>
            </div>
            <div class="acc-body">
                <p>Lorem Ipsum</p>
            </div>
        </div>

        <div class="acc-item 4">
            <div class="acc-header">
                <div class="float-right">
                    <i class="move-up"></i>
                    <i class="move-down"></i>
                </div>
                <div class="title">Aktiviti 4</div>
            </div>
            <div class="acc-body">
                <p>Lorem Ipsum</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $(".acc-header").click(function(){
            if ($(this).hasClass("active")){
                $(".acc-header").removeClass("active");
            } else {
                $(".acc-header").removeClass("active");
                $(this).addClass("active");
            }
        })

        $(".move-down").click(function(){
            $(".acc-header").removeClass("active");
            var $el = $(this).parent().parent().parent();

            if ($el.not(':last-child'))
                $el.next().after($el);
        });

        $(".move-up").click(function(){
            $(".acc-header").removeClass("active");
            var $el = $(this).parent().parent().parent();

            if ($el.not(':first-child'))
                $el.prev().before($el);
        });
    });
</script>
{% endblock %}

accord/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% block body %} {% endblock %}

<!-- Optional JavaScript -->
{% block script %} {% endblock %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

board/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    {% block body %} {% endblock %}

<!-- Optional JavaScript -->
    {% block script %} {% endblock %}
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

board/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}QasQus Board{% endblock %}

{% block body %}

    {% if form %}
    <div class="container">
        <p class="lead text-center">QasQus Message Form</p>
        <form action="{% url 'board:confirm' index=1 %}" method="post">
            {% csrf_token %}

            {{form|crispy}}

            <input id="submit" class="btn btn-outline-success btn-block" type="submit" value="Submit">
        </form>
    </div>
    {% endif %}

    {% if bucket %}
    <div class="container" style="background: #ddffdd">
        <p class="lead">Confirm your message!</p>
        <dl class="row">

            <dt class="col-sm-6">Author</dt>
            <dd class="col-sm-6">{{bucket.name}}</dd>

            <dt class="col-sm-6">Message</dt>
            <dd class="col-sm-6">{{bucket.text}}</dd>

        </dl>
        <br>
    </div>

    <div class="row d-flex justify-content-center">
        <form action="{% url 'board:index'%}" method="GET" class="form-group">
            {% csrf_token %}
            <input  type="submit" class="btn btn-outline-danger" id="cancel" value="CANCEL">
        </form>

        <form action="{% url 'board:confirm' index=2 %}" method="POST" class="form-group">
            {% csrf_token %}
            <input type="hidden" name="name" id="form_name" value="{{bucket.name}}">
            <input type="hidden" name="text" id="form_message" value="{{bucket.text}}">
            <input  type="submit" class="btn btn-outline-success" id="confirm" value="CONFIRM">
        </form>
    </div>

{% endif %}

    <div class="container" style="padding-top: 20px">
        <div class="container" id="board">
            {% for mess in msg %}
                <div class="container" id="message">
                    <blockquote class="blockquote text-center">
                        <p class="mb-0">{{mess.text}}</p>
                        <footer class="blockquote-footer">{{mess.name}}</footer>
                    </blockquote>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/accord.html
{% extends 'base.html' %}
{% load static %}

{% block title %}QasQus Accord{% endblock %}

{% block style %}
<style>
    .item-wrap {
        max-width: 500px;
        margin: 3rem auto 3rem auto;
    }

    .item-wrap .item .header{
        line-height: 2.5rem;
        cursor: pointer;
        padding: 0 3rem 0 1rem;
        text-align: left;
        border-bottom: 2px solid grey;
    }

    .item-wrap .item:last-child .header{
        border-bottom: none;
    }

    .item-wrap .item:first-child .header{
        border-top-left-radius: 5px;
        border-top-right-radius: 5px;
    }

    .item-wrap .item:last-child .header{
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .item-wrap .item .body{
        height: 0px;
        transition: all 0.5s ease;
        text-align: left;
        overflow: hidden;
    }

    .item-wrap .item .body p{
        padding: 1rem;
    }

    .item-wrap .item .header.active{
        border-bottom: 2px solid black;
    }

    .item-wrap .item .header.active + .body{
        height: 180px;
        transition: all 0.5s ease;
    }

    .item-wrap .item:last-child .header.active{
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }

    .item-wrap .item:last-child .body{
        border-bottom-left-radius: 5px;
        border-bottom-right-radius: 5px;
    }

    .comicFont{
        font-family: "Comic Sans MS",sans-serif;
    }

    .changeColor{
        background-image: url(https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fi0.kym-cdn.com%2Fentries%2Ficons%2Fmobile%2F000%2F022%2F940%2Fmockingspongebobbb.jpg&f=1&nofb=1);
    }
</style>
{% endblock %}

{% block body %}
<div class="text-center accord">
    <div class="item-wrap">
        <div class="item a1">
            <div class="header">
                <div class="float-right">
                    <i class="move-up">Up</i>
                    <i class="move-down">Down</i>
                </div>
                <div class="title">Aktiviti 1</div>
            </div>
            <div class="body">
                <p>Lorem Ipsum</p>
            </div>
        </div>

        <div class="item a2">
            <div class="header">
                <div class="float-right">
                    <i class="move-up">Up</i>
                    <i class="move-down">Down</i>
                </div>
                <div class="title">Aktiviti 2</div>
            </div>
            <div class="body">
                <p>Lorem Ipsum</p>
            </div>
        </div>

        <div class="item a3">
            <div class="header">
                <div class="float-right">
                    <i class="move-up">Up</i>
                    <i class="move-down">Down</i>
                </div>
                <div class="title">Aktiviti 3</div>
            </div>
            <div class="body">
                <p>Lorem Ipsum</p>
            </div>
        </div>

        <div class="item a4">
            <div class="header">
                <div class="float-right">
                    <i class="move-up">Up</i>
                    <i class="move-down">Down</i>
                </div>
                <div class="title">Aktiviti 4</div>
            </div>
            <div class="body">
                <p>Lorem Ipsum</p>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <button id="colorChange">Change Spongebob</button>
    <button id="styleChange">Change Style</button>
</div>

</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $("#colorChange").click(function(){
            $("body").toggleClass("changeColor");
            // console.log("colorChange wok");
        });

        $("#styleChange").click(function(){
            $(".accord").toggleClass("comicFont");
        });

        $(".header").click(function(){
            if ($(this).hasClass("active")){
                $(".header").removeClass("active");
            } else {
                $(".header").removeClass("active");
                $(this).addClass("active");
            }
        });

        $(".move-down").click(function(){
            var $el = $(this).parent().parent().parent();

            if ($el.not(':last-child'))
                $el.next().after($el);
        });

        $(".move-up").click(function(){
            var $el = $(this).parent().parent().parent();

            if ($el.not(':first-child'))
                $el.prev().before($el);
        });
    });
</script>
{% endblock %}

templates/auth.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Auth App
{% endblock %}

{% block body %} 

<div class="container option">
	{% if user.is_authenticated %}
	    <a id="dashboard" href="{% url 'authApp:dashboard' %}" type="button" class="btn btn-outline-primary btn-block">Dashboard</a>
	    <a id="logout" href="{% url 'authApp:logout' %}" type="button" class="btn btn-outline-danger btn-block">Log Out</a>
	{% else %}
	    <a id="login" href="{% url 'authApp:login' %}" type="button" class="btn btn-outline-success btn-block">Log In</a>
	    <a id="signup" href="{% url 'authApp:signup' %}" type="button" class="btn btn-outline-primary btn-block">Sign Up</a>
	{% endif %}
</div>

{% endblock %}

{% block script %} 
{% endblock %}

templates/book.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Google Book API
{% endblock %}

{% block body %} 
<div class="container" id="hallOfFame" style="margin-top: 20px; margin-bottom: 20px">
    <button onclick="leaderBoard()" type="button" class="btn btn-outline-success btn-block" data-toggle="modal" data-target="#leaderBoardModal" id="topLeaderBoard">Top Rated Books</button>
</div>

<!-- The Modal -->
<div class="modal fade" aria-labelledby="writeAMessageModal" aria-hidden="true" id="leaderBoardModal">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">

		  	<!-- Modal Header -->
		  	<div class="modal-header">
		    	<h4 class="modal-title">Top 5 Rated Books</h4>
		  	</div>

		  	<!-- Modal body -->
		  	<div class="modal-body table-responsive">
		    	
		    	<table class="table">
		    		
		    		<thead>
		    			<th scope="col">Name</th>
		    			<th scope="col">Author</th>
		    			<th scope="col">Like</th>
		    		</thead>

		    		<tbody id="leaderboard">
		    			
		    		</tbody>
		    	</table>
		  	</div>

		  	<!-- Modal footer -->
		  	<div class="modal-footer">
		    	<button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
		  	</div>

		</div>
	</div>
</div>

<div class="container" id="SearchDiv">

	<div class="input-group mb-3">

	  <input id="search" type="text" class="form-control" placeholder="Book Title" aria-label="Recipient's username" aria-describedby="button-addon2">

	  <div class="input-group-append">
	    <button class="btn btn-outline-secondary" type="button" id="searchButton">Search</button>
	  </div>
	</div>

	<div class="table-responsive">
	  <table class="table">

	    <thead>
	    	<th scope="col">No</th>
	    	<th scope="col">Image</th>
	    	<th scope="col">Name</th>
	    	<th scope="col">Author</th>
	    	<th scope="col"></th>
	    </thead>

	    <tbody id="results">

		    	<!-- <tr>
		    		<th scope="row">* nomer *</th>
		    		<td><img src="http://books.google.com/books/content?id=Gb460Bxyc5kC&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api"></td>
		    		<td>* nama *</td>
		    		<td>* author *</td>
		    		<td>
		    			<button type="button" id="id" title="title" author="author" class="likeButton btn btn-sm btn-success ml-3">Like</button>
		    		</td>
		    	</tr> -->
	    </tbody>
	  </table>

	</div>

</div>
{% endblock %}

{% block script %} 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<script>
	var leaderBoard;

     $(document).ready(function(){

     	leaderBoard =  function () {
     		$.ajax({
                url: "{% url "like:leaderboard" %}", 
                dataType: "json",

                success: function(data) {
                    console.log(data); // DEBUG
                    $('#leaderboard').empty();

                    for (i in data.leaderboards) {
                        $('#leaderboard').append(
                            '<tr id="contentModal"><td>' + data.leaderboards[i].title 
					    	+ '</td><td>' + data.leaderboards[i].authors 
					    	+ '</td><td id="likes">' + data.leaderboards[i].likes_count + '</td></tr>'
                        );
                    }                    
                },

                type: 'GET'
            });
     	}

        function bookSearch() {
            var searchValue = $('#search').val();
            console.log(searchValue);

            $.ajax({
                url: "https://www.googleapis.com/books/v1/volumes?q=" + searchValue, 
                dataType: "json",

                success: function(data) {
                    console.log(data) // DEBUG
                    for (i = 1; i <= data.items.length; i++) {
                        $('#results').append(
                        	'<tr> <th scope="row">' + i + '</th><td><img src="'
			    			+ data.items[i-1].volumeInfo.imageLinks.smallThumbnail + '""></td><td>'
			    			+ data.items[i-1].volumeInfo.title + '</td><td>'
			    			+ data.items[i-1].volumeInfo.authors + '</td><td>' 
			    			+ '<button type="button" id="'+ data.items[i-1].id +'" title="'+ data.items[i-1].volumeInfo.title 
			    			+'" author="'+ data.items[i-1].volumeInfo.authors 
			    			+'" class="likeButton btn btn-sm btn-success ml-3">Like</button></td></tr>'
			    		);
                   	}
                },

                type: 'GET'
            });
        }

        $("#searchButton").click(function(){
            $('#results').empty();
            bookSearch();
        });        

        function likeBook(id, title, author) {
            $.ajax({
                url: "{% url "like:like" %}", 
                data: { id: id, title: title, authors: author },

                success: function(book) {
                    console.log(book); // DEBUG                    
                    leaderBoard();
                },

                type: 'POST'
            });
        }

        $("#results").click(function(e) {
            if ($(e.target).hasClass("likeButton")){
                console.log("keklik nih buttonnya");
                var id = $(e.target).attr("id");
                var author = $(e.target).attr("author");
                var title = $(e.target).attr("title");

                console.log(id + title + author); // DEBUG
                likeBook(id, title, author);                 
            }                               
        });

    });
</script>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Auth App
{% endblock %}

{% block body %} 

<div class="container dashboard-body">
	{% if user.is_authenticated %}
	    <a id="home" href="{% url 'authApp:index' %}" type="button" class="btn btn-outline-primary btn-block">Home</a>
	    <a id="logout" href="{% url 'authApp:logout' %}" type="button" class="btn btn-outline-danger btn-block">Log Out</a>

	    <blockquote class="blockquote text-center">
		  <p class="mb-0" id="usernameP">Hello {{user.username}}!, welcome to my puny web</p>
		  <footer class="blockquote-footer">Me <cite title="Source Title">Who else :kekw:.</cite></footer>
		</blockquote>
	{% endif %}
</div>

{% endblock %}

{% block script %} 
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}QasQus Board{% endblock %}

{% block body %}

    {% if form %}
    <div class="container">
        <p class="lead text-center">QasQus Message Form</p>
        <form action="{% url 'board:confirm' index=1 %}" method="post">
            {% csrf_token %}

            {{form|crispy}}

            <input id="submit" class="btn btn-outline-success btn-block" type="submit" value="Submit">
        </form>
    </div>
    {% endif %}

    {% if bucket %}
    <div class="container" style="background: #ddffdd">
        <p class="lead">Confirm your message!</p>
        <dl class="row">

            <dt class="col-sm-6">Author</dt>
            <dd class="col-sm-6">{{bucket.name}}</dd>

            <dt class="col-sm-6">Message</dt>
            <dd class="col-sm-6">{{bucket.text}}</dd>

        </dl>
        <br>
    </div>

    <div class="row d-flex justify-content-center">
        <form action="{% url 'board:index'%}" method="GET" class="form-group">
            {% csrf_token %}
            <input  type="submit" class="btn btn-outline-danger" id="cancel" value="CANCEL">
        </form>

        <form action="{% url 'board:confirm' index=2 %}" method="POST" class="form-group">
            {% csrf_token %}
            <input type="hidden" name="name" id="form_name" value="{{bucket.name}}">
            <input type="hidden" name="text" id="form_message" value="{{bucket.text}}">
            <input  type="submit" class="btn btn-outline-success" id="confirm" value="CONFIRM">
        </form>
    </div>

{% endif %}

    <div class="container" style="padding-top: 20px">
        <div class="container" id="board">
            {% for mess in msg %}
                <div class="container" id="message">
                    <blockquote class="blockquote text-center">
                        <p class="mb-0">{{mess.text}}</p>
                        <footer class="blockquote-footer">{{mess.name}}</footer>
                    </blockquote>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}
	Auth App
{% endblock %}

{% block body %} 

<div class="container login-body">

	<div class="login-form">
		<form action="#" method="POST">
			{%csrf_token%}

			{{form|crispy}}
			<button id="login-button" type="submit" class="btn btn-outline-success btn-block">Login</button>
		</form>
	</div>

	<div class="container signup-button">
		<form action="{% url 'authApp:signup' %}">
		    <button id="signup-button" type="submit" class="btn btn-outline-primary btn-block">Sign Up Page</button>
		</form>
	</div>
	
</div>

{% endblock %}

{% block script %} 
{% endblock %}

templates/logout.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
	Auth App
{% endblock %}

{% block body %} 

<div class="container logout-body">

	<blockquote class="blockquote text-center">
	  <p class="mb-0">Logged out! Enjoy your day :)</p>
	  <footer class="blockquote-footer">Me <cite title="Source Title">Who else :kekw:.</cite></footer>
	</blockquote>

	<div class="container login-button">
		<form action="{% url 'authApp:login' %}">
		    <button id="login-button" type="submit" class="btn btn-outline-primary btn-block">Login Page</button>
		</form>
	</div>
</div>

{% endblock %}

{% block script %} 
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}
	Auth App
{% endblock %}

{% block body %} 

<div class="container signup-body">

	<div class="signup-form">
		<form  action="#" method="POST">
			{%csrf_token%}

			{{form|crispy}}
			<button id="signup-button" type="submit" class="btn btn-outline-success btn-block">Sign Up</button>
		</form>
	</div>

	<div class="container login-button">
		<form action="{% url 'authApp:login' %}">
		    <button id="login-button" type="submit" class="btn btn-outline-primary btn-block">Login Page</button>
		</form>
	</div>
	
</div>

{% endblock %}

{% block script %} 
{% endblock %}